language: python
python:
- 2.7
services:
- docker
install:
- pip install -U codecov
script:
- bash test-container.sh
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: papaemmelab
  password:
    secure: Rv50HrKa4G6LSkafrNKPwmJGC4QnmTunuJoJudIqhE96+QKCesnbQfJA32WZjHOkHes0CZMcFu9xpyLjUyNRYc6sE+HQvoL/dtiL3PbLbHNCBFryF8dTSt+LR4/CajUXbPdeRgZ4276Li6LMicwWU8tQAnHPPwI3MOCtZdiflxY7OSO487MZVZ3HxMg5+sF/7zYXrImR88eX81excYaCYz5yGHpz44YzqwN6Nn5YAL8Id+GEZ6TzHC5OVdI6q83VYDcesA1sx36ki0b2utQD3JJwkyLaQStZYjA/wIC88az+npzo1Ka2SyNABQJyHcBMBmKSfLQeSKVgeVU9lu5JflND4lT/9MchRcJ8U9egCuq7UKmpC1IcK1sb3bsiDB5Tc4G2y2cDYHKinQh49SPlxXiGYpTJuYvqhsUfzO7LBc0rujbux8HbdbwbMfsNNO1LNLy+bQ+Qcu+5VqSUjf1KBZeR2D71BeHBEKBmKj5AsVbky9DF18+Wva0/h8vkBLAFzxGGb25lLGzgpzVg1245drZwrkO2nQ0gUHXY/xvVUisCVrKC9tGkZ8+uQ7JQj5RIKPZvsUxRh1pWgM8/EVbbl/b5yiv2IABm9+pEx156HjgAII19sznhWwAB0ojTFjZe1j380AEL3tFT7Cdl2uzgLyYbG756kAFY7dXpxzowoUw=
  on:
    tags: true
    repo: papaemmelab/toil_caveman
    python: 2.7
    all_branches: true
