language: python

python:
  - 2.7

services:
  - docker

install:
  - pip install -U codecov

script:
  - bash test-container.sh

after_success:
  - codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  user: leukgen
  password:
    secure: mmb9UMHiyUqBXNIyD30e5eTVRsXIYu5ZtlAAkIkYYbxiurnBbGJkRpoEDOCmC8oBICFA6hrVyuZnErtnNiqMIDT3OGm0lLCdvVXX9RR3drD0cXXO3UTtl4/854oe5xGXSUfxGqlQOe+7C+n8FtsLVI8mo/lYiBYvdr+eo0pHyQEIqdCNZ5h7wxuRRy9h6fjQSelgBVa2PaZ2YY1vGETmbBkyPGrss+L2JNLl6mGa6qfPCGA7Jg+4WEqUeedRe2zKWjg0PTb68K8SxclEe6rWAeGFv8U5wn+jVKDNes5ZmlLUqH0q86ZwQBlJCm+r1fQaWCWAIKmOIf9b8S2YRm8cDYWkENtkp+MxXOatt3p9fi3i0gSs8Y4fwjx00IUV6mkof9NkKIdA1F5WrQW7z2qtASZyD3HJU+78vNTytpIVsjA9MI67+CsfEpz1AZPP60giH6aqWe5JGUKhO55UK/GOLAp2YZSt9P+AVYvoX9D8nLhGb2LVcp06QEC3Efy9tjV56ZQwuexk2ZZEIFl2575nk6f7IgwWYINmCFef2hsy6oMI2Te2P9sf34EJqiWAn53ffxqyoGB++3qyOdX1o1w2xhfDzz/9iZS1/lzkNgd+kMAfPB7+WTm50OcsSjXiD6kcA2u0kejuNpBMs8YsZ2hXonBEr3hGOYtQBJ2jhWcJQ00=
  on:
    tags: true
    repo: leukgen/toil_caveman
    python: 2.7
    branch: master
